#! /bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username $POSTGRES_USER --dbname $POSTGRES_DB <<-EOSQL
	CREATE USER $APP_DATABASE_USER WITH PASSWORD '$APP_DATABASE_PASSWORD';
	CREATE DATABASE $APP_DATABASE_NAME;
	GRANT ALL PRIVILEGES ON DATABASE $APP_DATABASE_NAME TO $APP_DATABASE_USER;
EOSQL
